version: '0.2'
language: en
ignorePaths:
  - '**/node_modules/**'
  - 'ideation/**'
  - '**/build/**'
  - '**/package-lock.json'
  - '**/*.lock'
  - 'example/*/android/**'
  - 'example/*/ios/**'
  - '.test-build/**'
dictionaryDefinitions:
  - name: project
    path: ./.cspell-project.txt
    addWords: true
dictionaries:
  - project
  - typescript
  - node
  - softwareTerms
