blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/khalid999devs/react-native-pose-detection/discussions
    about: Usage questions, ideas, and showing what you built
